spring.application.name=booking

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5434/lahlelo_booking_db
spring.datasource.username=postgres
spring.datasource.password=melusi
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: logging SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE