spring.application.name=booking

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5434/lahlelo_booking_db
spring.datasource.username=postgres
spring.datasource.password=melusi
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=none
=======
spring.jpa.hibernate.ddl-auto=update
>>>>>>> 602dc171e1b10551d9724b898562a3287ac8b4d2
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: logging SQL queries
logging.level.org.hibernate.SQL=DEBUG
<<<<<<< HEAD
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
=======
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Auto Email Services
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lahlelocreativeevents@gmail.com
spring.mail.password=jhguaslasqrjctle
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> 602dc171e1b10551d9724b898562a3287ac8b4d2
